### PR TITLE
Dev

### LINKED ISSUE #90: Grouping: shapes no more shown / lost(?) after editing
during the grouping mode it can happen that one finds mistakes in the shapes. after correcting the bos (edit shape), the grouping mode does not show any group anymore, although they were saved (using the "save" button).

### LINKED ISSUE #91: grouping buggy
The grouping functionality seems still buggy. i'm happy to arrange a short video chat for demonstration.

### LINKED ISSUE #92: Goups counter not working
the counter of "how many groups exist" on a certain fold does not work. it always says "0".

### LINKED ISSUE #96: cannot add new shape
while it was possible to remove superfluous shapes from fold jb_3795_1939-04-21_0005to0008 and adjuste the edges of existing shapes, and add some new shapes cf. #68 , adding yet another shape is not possible.
the fold has 89 shapes. if i add a new shape and hit "save", the save message appears ("90 shapes saved") but after reloading the fold that last shape does not appear and it says "89 shapes saved".

2021-07-31 14_49_43-Image Annotator demo with list and 1 more page - Profile 1 - Microsoft​ Edge

2021-07-31 14_50_13-Image Annotator demo with list and 1 more page - Profile 1 - Microsoft​ Edge

### LINKED ISSUE #101: edit shape not possible
editing shapes is no more possible. no matter, if existing or new shape. 
symptoms: after switch into edit-mode, the edge circles do appear, but moving them around does NOT affect the shape itself. dragging them around and saving the new coordinates of the edges is lost after a save.

### PR DESCRIPTION
**Pull request by line-o**
fixes #90 
fixes #91 
fixes #92 
fixes #96 
fixes #101

### CODE REVIEW

**Comment by line-o** [comment]
Good test link: https://ecpo.existsolutions.com/exist/apps/ecpo/annotator/?document=https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3798_1939-04-24_0002%25252B0003.tif/full/full/0/default.jpg

**Comment by MatthiasArnold** [comment]
probably only a minor thing: on the files page (e.g. April 1930) the timestamp in "Last modified" is not updated after submitting changes in the annotator. i did not find any other bug, so i'll merge the pr when this is fixed. thanks!

**Comment by line-o** [comment]
Hi @MatthiasArnold I was looking into the issue you reported here. The file list cannot know when a user - which is not necessarily the one that has the file listing open - finished editing a file. Only a reload of the listing will update the timestamp.

**Comment by MatthiasArnold** [comment]
Hello @line-o thanks for fixing that. we did try over some weeks when we tested the annotator with finetuning the boxed and doing the grouping of annotations from the april issues of 1920 ad 1930. at that time the dates were not updated. but it seems to work now. :)
thanks!

**Pull request merged**
